/******************************************************************************/
/* (c) 2025 Copyright, Real-Time Innovations, Inc. (RTI) All rights reserved. */
/*                                                                            */
/* RTI grants Licensee a license to use, modify, compile, and create          */
/* derivative works of the software solely for use with RTI Connext DDS.      */
/* Licensee may redistribute copies of the software provided that all such    */
/* copies are subject to this license.                                        */
/* The software is provided "as is", with no warranty of any type, including  */
/* any warranty for fitness for any purpose. RTI is under no obligation to    */
/* maintain or support the software.  RTI shall not be liable for any         */
/* incidental or consequential damages arising out of the use or inability to */
/* use the software.                                                          */
/*                                                                            */
/******************************************************************************/

module test {
    enum TestEnum {
        TEST_ENUM_VALUE_1,
        TEST_ENUM_VALUE_2,
        TEST_ENUM_VALUE_3
    };

    struct TestStruct {
        string member1;
        double member2;
        int8 member3;
        TestEnum member4;
    };

    union TestUnionSeq switch(TestEnum) {
        case TEST_ENUM_VALUE_1:   uint16 member1;
        case TEST_ENUM_VALUE_2:   boolean member2;
        default:   sequence<TestStruct, 5> member3;
    };

    union TestUnionArray switch(TestEnum) {
        case TEST_ENUM_VALUE_1:   uint16 member1;
        case TEST_ENUM_VALUE_2:   boolean member2;
        default:   TestStruct member3[5];
    };

    typedef sequence<char, 10> TSeq_String;
    typedef sequence<long, 10> TSeq_List;
    typedef sequence<TSeq_String, 5> TSeq_StringSeq;

    typedef char TArr_String[10];
    typedef long TArr_List[10];
    typedef TArr_String TArr_StringArr[5];

    module inttest1 {
        struct PubType {
            sequence<TestStruct> member1;
            sequence<TestEnum> member2;
            sequence<TestUnionSeq> member3;
            TestStruct member4[2];
            TestStruct member5;
            uint64 member6;
            TestEnum member7;
        };

        struct SubType {
            TestStruct member1[5];
            TestEnum member2[5];
            TestUnionArray member3[5];
            TestStruct member4[2];
            TestStruct member5;
            uint64 member6;
            TestEnum member7;
        };
    }; // module inttest1

    module inttest2 {
        struct PubType {
            TestStruct member1[5];
            TestEnum member2[5];
            TestUnionArray member3[5];
            sequence<TestStruct, 2> member4;
            TestStruct member5;
            uint64 member6;
            TestEnum member7;
        };

        struct SubType {
            sequence<TestStruct> member1;
            sequence<TestEnum> member2;
            sequence<TestUnionSeq> member3;
            sequence<TestStruct, 2> member4;
            TestStruct member5;
            uint64 member6;
            TestEnum member7;
        };
    }; // module inttest2

    module inttest3 {
        struct PubType {
            sequence<TSeq_String, 5> member1;
            sequence<TSeq_List, 5> member2;
            @optional TSeq_StringSeq member3;
        };

        struct SubType {
            TArr_String member1[5];
            TArr_List member2[5];
            @optional TArr_StringArr member3;
        };
    }; // module inttest3

    module inttest4 {
        struct PubType {
            TArr_String member1[5];
            TArr_List member2[5];
            @optional TArr_StringArr member3;
        };

        struct SubType {
            sequence<TSeq_String> member1;
            sequence<TSeq_List> member2;
            @optional TSeq_StringSeq member3;
        };
    }; // module inttest4
};
