typedef sequence<char, 10> T_String;
typedef sequence<long, 10> T_List;
typedef sequence<T_String, 5> T_StringSeq;

struct MyTypeWithSequences {
  sequence<T_String, 5> member1;
  sequence<T_List, 5> member2;
  @optional T_StringSeq member3;
};

