/******************************************************************************/
/* (c) 2025 Copyright, Real-Time Innovations, Inc. (RTI) All rights reserved. */
/*                                                                            */
/* RTI grants Licensee a license to use, modify, compile, and create          */
/* derivative works of the software solely for use with RTI Connext DDS.      */
/* Licensee may redistribute copies of the software provided that all such    */
/* copies are subject to this license.                                        */
/* The software is provided "as is", with no warranty of any type, including  */
/* any warranty for fitness for any purpose. RTI is under no obligation to    */
/* maintain or support the software.  RTI shall not be liable for any         */
/* incidental or consequential damages arising out of the use or inability to */
/* use the software.                                                          */
/*                                                                            */
/******************************************************************************/

module shapes{
	enum Type {
		TRIANGLE,
		CIRCLE,
		SQUARE
	}; //@Extensibility FINAL_EXTENSIBILITY

	enum Color {
		RED,
		BLUE,
		YELLOW
	}; //@Extensibility FINAL_EXTENSIBILITY

	struct Coordinates {
		long x;
		long y;
	}; //@Extensibility FINAL_EXTENSIBILITY

	enum ShapeFillKind {
		SOLID_FILL,
		TRANSPARENT_FILL,
		HORIZONTAL_HATCH_FILL,
		VERTICAL_HATCH_FILL
	};

	struct Shape {
		Type type; //@key
		Color color; //@key
	};//@Extensibility EXTENSIBLE_EXTENSIBILITY 

	struct ShapeExtended : Shape {
		long size;
		Coordinates coordinates;
		ShapeFillKind fillKind;
		string<128> name;
	};//@Extensibility EXTENSIBLE_EXTENSIBILITY 
};
