/******************************************************************************/
/* (c) 2020 Copyright, Real-Time Innovations, Inc. (RTI) All rights reserved. */
/*                                                                            */
/* RTI grants Licensee a license to use, modify, compile, and create          */
/* derivative works of the software solely for use with RTI Connext DDS.      */
/* Licensee may redistribute copies of the software provided that all such    */
/* copies are subject to this license.                                        */
/* The software is provided "as is", with no warranty of any type, including  */
/* any warranty for fitness for any purpose. RTI is under no obligation to    */
/* maintain or support the software.  RTI shall not be liable for any         */
/* incidental or consequential damages arising out of the use or inability to */
/* use the software.                                                          */
/*                                                                            */
/******************************************************************************/

/**
 * @file rtimqtt_types_adapter.idl
 * @brief IDL Types used by the MQTT Adapter.
 */

#include "rtiadapt_mqtt_types_client.idl"

module RTI { module RS { module MQTT {

    /**
     * @brief todo
     */
    struct BrokerConnectionConfig {
        /**
         * @brief todo
         */
        RTI::MQTT::ClientConfig         client;
    };

    /**
     * @brief todo
     */
    struct MessageReaderConfig {
        /**
         * @brief todo
         */
        RTI::MQTT::SubscriptionConfig   sub;
    };

    /**
     * @brief todo
     */
    struct MessageWriterConfig {
        /**
         * @brief todo
         */
        RTI::MQTT::PublicationConfig    pub;
    };

}; // module MQTT
}; // module RS
}; // module RTI
